### ISSUE TITLE
Create backup files(.tgz) in a jenkins pod. 

### ISSUE THREAD

**Issue by yanghoon** [cnpst/zcp-tools-backup#1]
It is too slow to copy jenkins_home through `kubectl cp` for creating a tgz file.
The main goal is to avoid using all PVC storage for backup.

But using the host(VM) storage is faster and there is no risk using all PVC storage also.
You must not forget to remove backup files after uploading to S3.

**Comment by lay126** [comment]
**HOW TO DO** 
AS IS : jenkins pod의 jenkins_home을 tools backup으로 kubectl copy한 후, 그곳에서 tar zip하여 S3에 업로드 한다. 이때, kubectl copy가 쓰는데 오랜 시간이 걸린다. 
TO BE : jenkins pod 안의 일반 폴더에 cp하여 그곳에서 tar를 하고 tools backup에 옮긴후 S3에 업로드한다. * 이때 반드시 일반 폴더에 copy, zip한 파일은 지워져야한다. 
(같은 용량이라도 낱개 파일보다는 1개의 파일이 옮기는것이 빠르기 때문)
